---
name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -t tests
